dist: trusty
sudo: required
services:
  - docker
addons:
  apt:
    sources:
      - git-core
      - ubuntu-toolchain-r-test
    packages:
      - git
env:
  - CXX=g++-4.9
before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
  - npm i -g eslint
language: node_js
node_js:
  - '7'
script:
  - bash ./deploy/deploy.sh
